// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdjtgnpldvhidpzxbbqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkanRnbnBsZHZoaWRwenhiYnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNzEyODcsImV4cCI6MjA3NDg0NzI4N30.W3ZAGFYXVyFGhyFcqihjLbJo2omWMNoTcxgGS7c8mxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});